name: w02 call a composite action
on:
  workflow_dispatch
jobs:   
  job1:
    name: j1 call a composite action
    uses: gh-workflows-project/reusable-workflows/.github/composite-actions/a01_hello@main
