name: w02 call a composite action
on:
  workflow_dispatch
jobs:   
  job1:
    runs-on: ubuntu-latest
    name: j1 call a composite action
    steps:
      - name: call the action
        uses: gh-workflows-project/reusable-workflows/.github/composite-actions/a01_hello@main
