# We must explicitly pass secrets to reusable workflows and actions, variables are passed by default to workflows but not to actions.
name: w06_secrets_vars context test reusable workflow and action with secrets and variables
on:
  workflow_dispatch
jobs:
  job1:
    name: j1 Test secrets_and_vars reusable workflow 
    uses: gh-workflows-project/reusable-workflows/.github/workflows/rw06_secrets_vars.yml@main
    secrets: # We have to explicitly pass secrets from the caller, however vars do not need explicit passing
      repo_s: ${{ secrets.repo_secret }}       
      org_s: ${{ secrets.org_secret }}    
  job2:
    name: j2 Test secrets_and_vars using an action
    runs-on: ubuntu-latest
    steps:
      - name: call the action in this step
        uses: gh-workflows-project/reusable-workflows/.github/composite-actions/a06_secrets_vars@main
        with: # we cannot really pass secrets as secrets to an action, passing as inputs works as 
              # they are masked even when passed as an input. We also HAVE to pass vars as input
          repo_s: ${{secrets.repo_secret}}       
          org_s: ${{secrets.org_secret}}
          repo_v: ${{vars.repo_var}}       
          org_v: ${{ars.org_var}}
  job3:
    name: j3 test dev environment 
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - run: |
          echo $${{vars.environment_var}}
          echo $${{vars.environment_secret}}  | sed 's/./& /g'  
  job4:
    name: j4 test stage environment 
    runs-on: ubuntu-latest
    environment:
      name: stage
    steps:
      - run: |
          echo $${{vars.environment_var}}
          echo $${{vars.environment_secret}}  | sed 's/./& /g'
          echo workflow done
      
