name: w07_scripts demo showing how to run scripts
on:
  workflow_dispatch
env:
  runjob: true 
jobs:   
  job1:
    name: j1 call a reusable workflow
    if: ${{env.runjob}}
    uses: gh-workflows-project/reusable-workflows/.github/workflows/rw07_scripts.yml@main
    with: # The script has to be in the caller workflow repo
      bash_script: scripts/hello.sh
      py_script: scripts/helly.py
      js_script: scripts/hello.js
      
