name: w07_scripts demo showing how to run scripts
on:
  workflow_dispatch
jobs:   
  job1:
    name: j1 call a reusable workflow
    uses: gh-workflows-project/reusable-workflows/.github/workflows/rw07_scripts.yml@main
    with: # The scripts repo is either the caller workflow repo or the callee workflow repo
    #  script_repo: caller_repo 
    #  script repo: called repo
      bash_script: scripts/hello.sh
      py_script: scripts/hello.py
      js_script: scripts/hello.js
      
