name: w08_read_data  use composite-actions to read a json and a yaml file 
on:
  workflow_dispatch
jobs:   
  job1:
    name: read json
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.read_file.outputs.data }}
    steps:
      - name: call the action
        id: read_file      
        uses: gh-workflows-project/reusable-workflows/.github/composite-actions/a08_read_json_data@main
        with:
         file_path:  data/w08.json
  job2:
    name: read yaml
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.read_file.outputs.data }}
    steps:
      - name: call the action
        id: read_file   
        uses: gh-workflows-project/reusable-workflows/.github/composite-actions/a08_read_yaml_data@main
        with:
         file_path: data/w08.yml
  job3: 
    name: read output from the above jobs
    runs-on: ubuntu-latest
    needs: [job1,job2]
    env:
      json_file_data: ${{needs.job1.outputs.data}} 
      yaml_file_data: ${{needs.job2.outputs.data}} 
    steps:
      - name: log output from json
      # pay attention to use of single quotes.
        run: | 
          echo '${{env.json_file_data}}' | jq '.'
          echo '${{env.json_file_data}}' | jq '.level0.level1.level2.level3.level4.list[0]'  
          myvar=$(echo '${{env.json_file_data}}' | jq '.level0.level1.level2.level3.level4')
          echo $myvar
          echo $myvar | jq '.list'
      - name: log output from yaml
        run: | 
          echo '${{env.yaml_file_data}}' | jq '.'
          echo '${{env.yaml_file_data}}' | jq '.level0.level1.level2.level3.level4.list[0]'  
          myvar=$(echo '${{env.yaml_file_data}}' | jq '.level0.level1.level2.level3.level4')
          echo $myvar
          echo $myvar | jq '.list'
      
      
  
         
